language: node_js
node_js:
  - '6'
  - '8'

cache:
  directories:
    - "node_modules"

before_script:
  - npm run lint

after_success:
  - npm run coverage

notifications:
  email:
    on_success: never